In [27]:
import numpy as np
import matplotlib.pyplot as plt

In [28]:
n = 100
Teta = 4
B = 0.95
etta = np.random.uniform(0,1,n)
sample = (1-etta)**(1/(1-Teta))
print(sample)

[1.90000049 1.2529339  1.25142108 1.00424146 1.20037321 1.21598057
 1.36813309 1.03195903 1.32243868 1.45129278 1.02392989 1.95057775
 1.10753698 1.05700786 1.48411493 1.04265307 1.87633677 1.30742052
 1.12098386 1.08519125 1.21665962 1.68011817 1.3134333  2.04900649
 1.17818913 1.17736718 2.00435311 1.22546836 1.0086707  1.01354775
 1.06377544 1.94192586 1.88503029 1.8297994  1.14559365 1.06405855
 1.95743793 1.27940612 1.04224209 1.59707655 1.19917522 1.11706755
 1.14463324 1.14248878 1.01229402 1.0543772  1.01406503 1.07081721
 1.10170368 1.18008665 1.52282304 1.07191726 1.13577703 1.12098992
 1.58014168 1.15420871 1.38021511 1.21808876 1.32300442 1.27720183
 1.82560369 1.98845975 1.99703882 1.01055834 1.20529121 1.64915176
 1.27174366 1.50277145 4.1121292  1.13464282 1.75764233 1.55878721
 1.04833451 2.93741291 1.152925   3.10066783 1.10008927 3.14852788
 1.30958574 1.0628721  1.17025253 1.18562081 4.11689172 1.83609394
 1.3272518  1.78144269 1.06780546 1.4848806  1.63542051 1.1695

In [29]:
S = 0
for i in sample:
  S += np.log(i)
Teta = (n/S)+1
print(Teta)

4.054748060793482


In [30]:
a = -1.96*(((2**(1/(Teta-1)))*np.log(2))/((Teta-1)*(n**(1/2))))+2**(1/(Teta-1))
b = 1.96*(((2**(1/(Teta-1)))*np.log(2))/((Teta-1)*(n**(1/2))))+2**(1/(Teta-1))
L_confidence_interval_for_mediana = b-a
print(f"confidence_interval_for_mediana ({a},{b})")

confidence_interval_for_mediana (1.1989124266955324,1.310516765931809)


In [31]:
a = -1.96*((Teta-1)/(n**(1/2)))+Teta
b = 1.96*((Teta-1)/(n**(1/2)))+Teta
L_confidence_interval_for_param = b-a
print(f"confidence_interval_for_param ({a},{b})")


confidence_interval_for_param (3.4560174408779596,4.6534786807090045)


In [32]:
N = 10000
Teta = 4
all_samples = []
all_tetas = []
for _ in range(N):
  etta = np.random.uniform(0,1,n)
  sample_ = (1-etta)**(1/(1-Teta))
  all_samples.append(sample_)
  S = 0
  for i in sample_:
    S += np.log(i)
    teta_ = (n/S)+1
  all_tetas.append(teta_)
all_samples = np.array(all_samples)
all_tetas = np.array(all_tetas)
print(all_samples)
print(all_samples.shape)


[[4.28835164 1.00619305 1.07871995 ... 1.55124897 1.15747983 1.08469044]
 [1.35046467 1.22580108 1.07008268 ... 1.26212041 1.23863963 1.34346434]
 [1.38538527 1.97285322 1.12851719 ... 1.08855627 1.43587231 1.21174313]
 ...
 [1.38915046 1.1212064  1.22981649 ... 1.07774086 1.44155925 1.28902575]
 [1.25486177 1.76904236 1.15921663 ... 1.14048855 2.03649964 1.64529844]
 [2.02529483 1.21214724 1.24233735 ... 4.00598878 1.40951525 1.01309053]]
(10000, 100)


In [33]:
print(all_tetas)
print(all_tetas.shape)

[4.05080398 3.6850306  3.98765343 ... 3.7753085  4.13237845 3.47210709]
(10000,)


In [34]:
all_tetas.sort()
all_tetas

array([3.1182164 , 3.14979935, 3.18355334, ..., 5.43150038, 5.4927767 ,
       5.56681885])

In [35]:
K1 = int(N*(1-B)/2)
K2 = int(N*(1+B)/2)
parametric_bootstrap_interval = (all_tetas[K1], all_tetas[K2])
L_parametric_bootstrap_interval = all_tetas[K2]-all_tetas[K1]
parametric_bootstrap_interval

(np.float64(3.4901981463113536), np.float64(4.69150963767674))

In [36]:
N = 1000
Teta = 4
all_samples = []
all_tetas = []
for _ in range(N):
  sample_ = np.random.choice(sample, size=n, replace=True)
  all_samples.append(sample_)
  S = 0
  for i in sample_:
    S += np.log(i)
    teta_ = (n/S)+1
  all_tetas.append(teta_)
all_samples = np.array(all_samples)
all_tetas = np.array(all_tetas)
print(all_samples)
print(all_samples.shape)
print(all_tetas)
print(all_tetas.shape)
all_tetas.sort()
all_tetas

K1 = int(N*(1-B)/2)
K2 = int(N*(1+B)/2)

nonparametric_bootstrap_interval = (Teta + all_tetas[K1], Teta + all_tetas[K2])
L_nonparametric_bootstrap_interval = all_tetas[K2] - all_tetas[K1]
nonparametric_bootstrap_interval

[[1.30199523 1.3272518  1.00424146 ... 1.06780546 1.01354775 3.10066783]
 [1.21808876 1.15420871 2.12213267 ... 1.06405855 1.8297994  1.06780546]
 [1.63542051 1.07191726 1.63542051 ... 1.21598057 1.18008665 1.2529339 ]
 ...
 [1.63542051 1.95743793 1.0543772  ... 1.0525553  1.14559365 1.152925  ]
 [1.01406503 1.03195903 1.63542051 ... 1.04224209 1.04833451 1.88503029]
 [1.05700786 1.87633677 1.95743793 ... 2.19524111 1.0525553  1.78144269]]
(1000, 100)
[3.59849262 4.01546299 4.09417326 3.92677252 4.23238219 4.5001421
 3.79758404 4.18072949 5.33930595 4.02374888 4.2316685  4.07894005
 4.12504686 4.83471669 3.35398084 3.98921696 3.8240775  4.01768359
 4.15890297 4.24003675 4.7011128  3.7982365  3.7658034  3.84515173
 4.38586245 3.80020918 3.89559472 3.43386761 3.8138025  3.84038023
 3.80862566 4.06777037 3.89356402 4.08894707 4.99089292 4.22579104
 3.56227911 3.78913996 3.88594588 3.96242402 4.56112673 4.01838161
 3.85070874 3.93278584 4.22110963 4.15467582 4.10380426 3.89202621
 3.549825

(np.float64(7.557395973138311), np.float64(8.725252987770043))

In [37]:
L_min_interval = min(L_confidence_interval_for_mediana, L_confidence_interval_for_param, L_parametric_bootstrap_interval)
L_max_interval = max(L_confidence_interval_for_mediana, L_confidence_interval_for_param, L_parametric_bootstrap_interval)
print(f"Длина доверительного интервала для медианы: {L_confidence_interval_for_mediana}", 
      f"Длина доверительного интервала для параметра: {L_confidence_interval_for_param}",
      f"Длина параметрического бутстраповского доверительного интервала: {L_parametric_bootstrap_interval}", 
      f"Длина непараметрического бутстраповского доверительного интервала: {L_nonparametric_bootstrap_interval}", 
      f"Макс. длина интервала: {L_max_interval}", f"Мин. длина интервала: {L_min_interval}", sep="\n")

Длина доверительного интервала для медианы: 0.11160433923627666
Длина доверительного интервала для параметра: 1.197461239831045
Длина параметрического бутстраповского доверительного интервала: 1.2013114913653862
Длина непараметрического бутстраповского доверительного интервала: 1.1678570146317324
Макс. длина интервала: 1.2013114913653862
Мин. длина интервала: 0.11160433923627666
